# Generated by Django 3.1.2 on 2021-07-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Roll_No',
            field=models.IntegerField(),
        ),
    ]
